kind: ConfigMap
apiVersion: v1
metadata:
  name: bootcamp-config
data:
  MESSAGE: 'Es hat spaß gemacht mit euch! Ich hoffe ihr hattet genauso viel vergügen wie ich. Bis dann DGN - Kaarst'
  NAME: Aliriza Tasdemir
  ROLE: Viada Trainer
