apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/manifests

patches:
  - path: patch-configmap.yaml

labels:
  - pairs:
      someName: someValue
      owner: alice
      app: bingo
